model:
  class: LGBModel
  module_path: qlib.contrib.model.gbdt
  kwargs:
    loss: mse
    colsample_bytree: 0.9
    learning_rate: 0.1
    subsample: 0.9
    lambda_l1: 205.6999
    lambda_l2: 580.9768
    max_depth: 8
    num_leaves: 250
    num_threads: 20

dataset:
  class: DatasetH
  module_path: qlib.data.dataset

data_handler:
  class: Alpha158
  module_path: qlib.contrib.data.handler

