image = "/capstor/scratch/cscs/ljiayong/enroot_images/qlib.sqsh"
mounts = ["/capstor/scratch/cscs/ljiayong:/capstor/scratch/cscs/ljiayong",
          "/users/ljiayong/projects/qlib:/users/ljiayong/projects/qlib",
          ]
workdir = "/users/ljiayong/projects/qlib"
writable = true

[env]
NVIDIA_VISIBLE_DEVICES = "all"
NVIDIA_DRIVER_CAPABILITIES = "compute,utility"
